### ISSUE TITLE
Finish the ValidationBlock

### ISSUE THREAD

**Issue by woutervanranst** [woutervanranst/Arius#26]

**Comment by woutervanranst** [comment]
```
05:59:41 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetCreateIfNotExistsBlock - BinaryFile PIC_0328.JPG already exists. No need to process.
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetCreateIfNotExistsBlock - BinaryFile PIC_0314.JPG already exists. No need to process.
05:59:41 fail: Arius.CommandLine.ValidateBlockProvider[0] ERRORTODO System.InvalidOperationException: something is wrong    at Arius.CommandLine.ValidateBlockProvider.<GetBlock>b__4_0(PointerFile pointerFile) in /src/Arius/CommandLine/ArchiveCommandExecutorBlocks.cs:line 933
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetReconcileBlock - BinaryFile PIC_0334.JPG already created. Passing item to next block.
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetReconcileBlock - BinaryFile PIC_0258.JPG already created. Passing item to next block.
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetReconcileBlock - BinaryFile PIC_0287.JPG already created. Passing item to next block.
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetCreateIfNotExistsBlock - BinaryFile PIC_0247.JPG already exists. No need to process.
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetCreateIfNotExistsBlock - BinaryFile PIC_0280.JPG already exists. No need to process.
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetCreateIfNotExistsBlock - BinaryFile PIC_0263.JPG already exists. No need to process.
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetReconcileBlock - BinaryFile PIC_0279.JPG already created. Passing item to next block.
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetReconcileBlock - BinaryFile PIC_0272.JPG already created. Passing item to next block.
05:59:42 fail: Arius.AriusCommandService[0] Unhandled exception System.InvalidOperationException: something is wrong    at Arius.CommandLine.ValidateBlockProvider.<GetBlock>b__4_0(PointerFile pointerFile) in /src/Arius/CommandLine/ArchiveCommandExecutorBlocks.cs:line 933    at Arius.CommandLine.ArchiveCommandExecutor.Execute() in /src/Arius/CommandLine/ArchiveCommandExecutor.cs:line 276    at Arius.AriusCommandService.<StartAsync>b__10_1() in /src/Arius/Console/Program.cs:line 226
05:59:42 info: Arius.AriusCommandService[0] Deleting tempdir...
05:59:42 info: Arius.AriusCommandService[0] Deleting tempdir... done
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetReconcileBlock - BinaryFile PIC_0320.JPG already created. Passing item to next block.
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetReconcileBlock - BinaryFile PIC_0319.JPG already created. Passing item to next block.
05:59:42 info: Microsoft.Hosting.Lifetime[0] Application is shutting down...
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetCreateIfNotExistsBlock - BinaryFile PIC_0292.JPG already exists. No need to process.
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetReconcileBlock - BinaryFile PIC_0323.JPG already created. Passing item to next block.
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetReconcileBlock - BinaryFile PIC_0324.JPG already created. Passing item to next block.
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetReconcileBlock - BinaryFile PIC_0246.JPG already created. Passing item to next block.
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetCreateIfNotExistsBlock - BinaryFile PIC_0321.JPG already exists. No need to process.
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetCreateIfNotExistsBlock - BinaryFile PIC_0252.JPG already exists. No need to process.
05:59:42 info: Arius.CommandLine.CreateManifestBlockProvider[0] GetReconcileBlock - BinaryFile PIC_0267.JPG already created. Passing item to next block.
05:59:42 fail: Arius.CommandLine.CreateManifestBlockProvider[0] ERRORTODO System.AggregateException: An error occurred while writing to logger(s). (Cannot access a disposed object. Object name: 'FileLoggerProcessor'.)  ---> System.ObjectDisposedException: Cannot access a disposed object. Object name: 'FileLoggerProcessor'.    at Karambolo.Extensions.Logging.File.FileLoggerProcessor.Enqueue(FileLogEntry entry, ILogFileSettings fileSettings, IFileLoggerSettings settings)    at Karambolo.Extensions.Logging.File.FileLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)    at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)    --- End of inner exception stack trace ---    at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)    at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)    at Arius.CommandLine.ProcessIfNotExistBlocksProvider`1.<GetReconcileBlock>b__5_0(Object item) in /src/Arius/CommandLine/ArchiveCommandExecutorBlocks.cs:line 295
05:59:42 fail: Arius.CommandLine.CreateManifestBlockProvider[0] ERRORTODO System.AggregateException: An error occurred while writing to logger(s). (Cannot access a disposed object. Object name: 'FileLoggerProcessor'.)  ---> System.ObjectDisposedException: Cannot access a disposed object. Object name: 'FileLoggerProcessor'.    at Karambolo.Extensions.Logging.File.FileLoggerProcessor.Enqueue(FileLogEntry entry, ILogFileSettings fileSettings, IFileLoggerSettings settings)    at Karambolo.Extensions.Logging.File.FileLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)    at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)    --- End of inner exception stack trace ---    at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)    at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)    at Arius.CommandLine.ProcessIfNotExistBlocksProvider`1.<GetCreateIfNotExistsBlock>b__4_0(T item) in /src/Arius/CommandLine/ArchiveCommandExecutorBlocks.cs:line 240
```

**Comment by woutervanranst** [comment]
Run of `arius-20210520-053801`

**Comment by woutervanranst** [comment]
* properly await the validation, if it crashes
* Make the validation non-crashing
